### ISSUE TITLE
Bug in Styling of Forget-Password Page

### ISSUE THREAD

**Issue by navidJadid** [navidJadid/openease_flask#14]
The current Forget-Password Page looks like this:

![Screenshot from 2019-08-29 15-33-45](https://user-images.githubusercontent.com/43848620/63944899-bd265800-ca72-11e9-86eb-58b2355dd202.png)

Please fix the header of the box. Probably just need to apply some styling in the file-specific css.

**Comment by Rollson** [comment]
fixed
