### ISSUE TITLE
External Files loaded twice

### ISSUE THREAD

**Issue by navidJadid** [navidJadid/openease_flask#15]
Why do these files need to be loaded twice? `main.html` extends `layout.html`, wouldn't loading once suffice?

https://github.com/navidJadid/openease_flask/blob/76fae97b25512f6ae4743b19e0c3e7bd0b53101d/webrob/templates/layout.html#L7-L14

https://github.com/navidJadid/openease_flask/blob/76fae97b25512f6ae4743b19e0c3e7bd0b53101d/webrob/templates/main.html#L5-L11

**Comment by Rollson** [comment]
Fixed
