### ISSUE TITLE
Split up the setting_test.py

### ISSUE THREAD

**Issue by seba90** [navidJadid/openease_flask#19]
@Rollson 

The test file is too larger. Can you move the tests in additional test files. For instance, one test file can just the if the tokens are set. Another one can check the configuration for the database.
Feel free to decide by yourself how many test files you want to create.
Just keep in mind that the test files represent one and the same concept/idea of your testing scenario.

https://github.com/navidJadid/openease_flask/blob/c79ead447bb817978ca9e412308ee7ce23a56c78/webrob/test/config/settings_test.py#L37

**Comment by Rollson** [comment]
Solved
