### ISSUE TITLE
Not required reference assert

### ISSUE THREAD

**Issue by seba90** [navidJadid/openease_flask#26]
@Rollson 

Why are you doing the reference assert to testDB ?
As far as I can tell you are not making a deep copy of db.
You store just the reference.
If you want to have a copy of db, you need to make a deep copy of it.

https://github.com/navidJadid/openease_flask/blob/12c5af9f0757cc0d6bcc4b5e80fdf8afa9f1480c/webrob/test/models/teach_test.py#L8

**Comment by Rollson** [comment]
fixed
